all:
	@echo "!!! Note that this was not tested as I'm currently working on Windows and I'd rather use bazel! !!!"
	${CC} -Iinc -Llib -lcomplex_polynomials -o c_caller

run:
	./c_caller

clean:
	rm c_caller

.PHONY: all run clean
